# Generated by Django 5.2.5 on 2025-08-18 01:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureEngineering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('input_features', models.JSONField(default=list)),
                ('output_features', models.JSONField(default=list)),
                ('transformations', models.JSONField(default=list)),
                ('scaling_method', models.CharField(choices=[('standard', 'Standard Scaler'), ('minmax', 'Min-Max Scaler'), ('robust', 'Robust Scaler'), ('none', 'No Scaling')], default='standard', max_length=50)),
                ('encoding_method', models.CharField(choices=[('onehot', 'One-Hot Encoding'), ('label', 'Label Encoding'), ('target', 'Target Encoding'), ('none', 'No Encoding')], default='onehot', max_length=50)),
                ('validation_rules', models.JSONField(default=dict)),
                ('data_quality_checks', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Engineering',
                'verbose_name_plural': 'Feature Engineering',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('model_type', models.CharField(choices=[('cost_prediction', 'Cost Prediction'), ('timeline_prediction', 'Timeline Prediction'), ('risk_assessment', 'Risk Assessment'), ('quality_prediction', 'Quality Prediction'), ('safety_prediction', 'Safety Prediction'), ('change_order_impact', 'Change Order Impact')], max_length=50)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('training', 'Training'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('algorithm', models.CharField(max_length=100)),
                ('hyperparameters', models.JSONField(default=dict)),
                ('feature_columns', models.JSONField(default=list)),
                ('target_column', models.CharField(max_length=100)),
                ('model_file_path', models.CharField(blank=True, max_length=500)),
                ('scaler_file_path', models.CharField(blank=True, max_length=500)),
                ('encoder_file_path', models.CharField(blank=True, max_length=500)),
                ('accuracy', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('precision', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('recall', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('f1_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('mae', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_trained', models.DateTimeField(blank=True, null=True)),
                ('training_data_size', models.IntegerField(blank=True, null=True)),
                ('validation_data_size', models.IntegerField(blank=True, null=True)),
                ('training_duration', models.DurationField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ML Model',
                'verbose_name_plural': 'ML Models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelTrainingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_run_id', models.CharField(max_length=100, unique=True)),
                ('training_accuracy', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('validation_accuracy', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('training_loss', models.FloatField()),
                ('validation_loss', models.FloatField()),
                ('precision', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('recall', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('f1_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('epochs', models.IntegerField()),
                ('batch_size', models.IntegerField()),
                ('learning_rate', models.FloatField()),
                ('hyperparameters', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('data_size', models.IntegerField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_history', to='ai_models.mlmodel')),
            ],
            options={
                'verbose_name': 'Model Training History',
                'verbose_name_plural': 'Model Training History',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_features', models.JSONField()),
                ('input_data_hash', models.CharField(max_length=64)),
                ('prediction_value', models.FloatField()),
                ('prediction_confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('prediction_interval_lower', models.FloatField(blank=True, null=True)),
                ('prediction_interval_upper', models.FloatField(blank=True, null=True)),
                ('actual_value', models.FloatField(blank=True, null=True)),
                ('prediction_error', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.CharField(blank=True, max_length=100)),
                ('user_id', models.CharField(blank=True, max_length=100)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ai_models.mlmodel')),
            ],
            options={
                'verbose_name': 'Model Prediction',
                'verbose_name_plural': 'Model Predictions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model', 'created_at'], name='ai_models_m_model_i_104fd8_idx'), models.Index(fields=['input_data_hash'], name='ai_models_m_input_d_b6f054_idx')],
            },
        ),
    ]
